[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sourceLens"
version = "0.1.1"
description = "AI-powered tool to generate tutorials from source code or codebases."
readme = "README.md"
authors = [
  { name = "Jozef Darida", email = "darijo2@yahoo.com" },
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    # "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)", # ODSTRÁNENÉ
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Documentation",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    # "pocketflow>=0.0.1", # ODSTRÁNENÉ - integrované do projektu
    "PyYAML>=6.0",
    "requests>=2.28.0",
    "GitPython>=3.1.0",
    "google-cloud-aiplatform>=1.25.0",
    "google-generativeai>=0.8.0",
    # "anthropic>=0.20.0",
    # "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "attrs>=21.3.0",
    "jsonschema>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/darijo2yahoocom/sourceLensAI"
Repository = "https://github.com/darijo2yahoocom/sourceLensAI"

[project.scripts]
sourcelens = "sourcelens.main:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "ruff>=0.1.0",
    "mypy>=1.0",
    "pre-commit>=3.0",
    "build>=0.10.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E", "W", "F", "I", "C", "B", "D", "UP", "YTT", "ANN", "ASYNC",
    "S", "BLE", "FBT", "NPY", "PD", "PGH", "PL", "PT", "PTH", "RSE",
    "RET", "SLF", "SIM", "TID", "TCH",
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
packages = ["sourcelens"]
namespace_packages = true

# End of pyproject.toml