# Copyright (C) 2025 Jozef Darida (LinkedIn/Xing)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Initialize the diagrams prompts package.

This package consolidates prompt formatting functions for various types
of diagrams generated by SourceLens, such as relationship flowcharts,
class diagrams, package diagrams, and sequence diagrams. It also includes
functions for algorithmically generating certain diagrams like the file
structure diagram and provides shared guidelines for inline diagrams.
"""

# Import from specific modules within this package
from sourcelens.prompts.diagrams._inline_diagram_guidelines import (
    INLINE_MERMAID_DIAGRAM_GUIDELINES_TEXT,
)
from sourcelens.prompts.diagrams.class_diagram_prompts import (
    format_class_diagram_prompt,
)
from sourcelens.prompts.diagrams.file_structure_diagram import (
    generate_file_structure_mermaid,
)
from sourcelens.prompts.diagrams.package_diagram_prompts import (
    format_package_diagram_prompt,
)
from sourcelens.prompts.diagrams.relationship_flowchart_prompts import (
    format_relationship_flowchart_prompt,
)
from sourcelens.prompts.diagrams.sequence_diagram_prompts import (
    format_sequence_diagram_prompt,
)

# Removed problematic circular import:
# from sourcelens.prompts.chapter_prompts import ChapterPrompts

__all__: list[str] = [
    "format_class_diagram_prompt",
    "format_package_diagram_prompt",
    "format_relationship_flowchart_prompt",
    "format_sequence_diagram_prompt",
    "generate_file_structure_mermaid",
    "INLINE_MERMAID_DIAGRAM_GUIDELINES_TEXT",
]

# End of src/sourcelens/prompts/diagrams/__init__.py
